### PR TITLE
Rust round robin server

### PR DESCRIPTION
**Pull request by xekoukou**
Very low stddev but comparable mean to rust server.

### CODE REVIEW

**Comment by jonhoo** [comment]
From what I can tell, this is pretty much identical to #19, except that instead of giving streams to a thread that is free, it just assigns them in round-robin order? If this is indeed the only difference, then #19 seems strictly better.

**Comment by xekoukou** [comment]
Sorry, the name is misleading. I changed the handle_client function to only handle one iteration of the loop. Then the thread switches to a new client. This is the reason that the stddev here is the smallest possible from all the servers.

I thought that this way, we could have the servers work on another client till the previous client was to send the next challenge, thus not waiting the back and forth packet latency, not doing anything.

In my machine, it seams that the latency due to thread context switching was the significant time. 

If we had networks with high latency, this would be the ideal solution because the latency of the network would be the significant part.

**Comment by xekoukou** [comment]
A good way to check networks with high latency is to put a sleep command inside the client loop.

Then benchmark the servers and see who does best.

**Comment by jonhoo** [comment]
Continued in #22.

**Pull request closed without merging**
